controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    missile_controller:
      type: velocity_controllers/JointGroupVelocityController

# Gripper
missile_controller:
  ros__parameters:
    joints:
      - Arm_joint
      - turret_joint
      - Bullet_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity